/* Generated by tools/scripttokens.py -- do not edit.
 *
 * The 185 script keywords, from the table ScriptLookupToken
 * walks at 0x00487C90. docs/scripttokens.md is the same data
 * as prose. Ids 15 and 31 are absent from the table, so no
 * constant exists for them and nothing the tokeniser produces
 * can carry them.
 */
#ifndef AM2_SCRIPTTOKENS_H
#define AM2_SCRIPTTOKENS_H

#define AM2_TOK_LPAREN             1
#define AM2_TOK_RPAREN             2
#define AM2_TOK_COMMA              3
#define AM2_TOK_LT                 4
#define AM2_TOK_LE                 5
#define AM2_TOK_EQ                 6
#define AM2_TOK_GT                 7
#define AM2_TOK_GE                 8
#define AM2_TOK_NE                 9
#define AM2_TOK_LBRACE            10
#define AM2_TOK_RBRACE            11
#define AM2_TOK_AMP               12
#define AM2_TOK_PLUS              13
#define AM2_TOK_TESTVAR           14
#define AM2_TOK_GREEN             16
#define AM2_TOK_TAN               17
#define AM2_TOK_BLUE              18
#define AM2_TOK_GREY              19
#define AM2_TOK_ME                20
#define AM2_TOK_ARMY0             21
#define AM2_TOK_ARMY1             22
#define AM2_TOK_ARMY2             23
#define AM2_TOK_ARMY3             24
#define AM2_TOK_PRELOADSPRITE     25
#define AM2_TOK_PAD               26
#define AM2_TOK_PADON             27
#define AM2_TOK_PADOFF            28
#define AM2_TOK_EVERYTHING        29
#define AM2_TOK_ITEM              30
#define AM2_TOK_SARGE             32
#define AM2_TOK_UNIT              33
#define AM2_TOK_TROOPER           34
#define AM2_TOK_TANK              35
#define AM2_TOK_VEHICLE           36
#define AM2_TOK_JEEP              37
#define AM2_TOK_HALFTRACK         38
#define AM2_TOK_CONVOY            39
#define AM2_TOK_BOAT              40
#define AM2_TOK_GROUNDVEHICLE     41
#define AM2_TOK_NPC               42
#define AM2_TOK_DELAY             43
#define AM2_TOK_IF                44
#define AM2_TOK_THEN              45
#define AM2_TOK_ALLOF             46
#define AM2_TOK_BUTNOT            47
#define AM2_TOK_INORDER           48
#define AM2_TOK_REPEAT            49
#define AM2_TOK_COUNT             50
#define AM2_TOK_OF                51
#define AM2_TOK_AFTER             52
#define AM2_TOK_AND               53
#define AM2_TOK_SEQUENTIAL        54
#define AM2_TOK_RANDOM            55
#define AM2_TOK_ONOBJSTATE        56
#define AM2_TOK_KILLED            57
#define AM2_TOK_HIT               58
#define AM2_TOK_HEALED            59
#define AM2_TOK_BY                60
#define AM2_TOK_PICKEDUP          61
#define AM2_TOK_DROPPED           62
#define AM2_TOK_TIMEABSOLUTE      63
#define AM2_TOK_SHOWMESSAGE       64
#define AM2_TOK_SHOWBITMAP        65
#define AM2_TOK_SHOWBITMAPNOPAUSE  66
#define AM2_TOK_PLAYSOUND         67
#define AM2_TOK_PLAYITEMSOUND     68
#define AM2_TOK_PLAYMUSIC         69
#define AM2_TOK_TRACEVAR          70
#define AM2_TOK_SHOWFAILURE       71
#define AM2_TOK_SHOWPDA           72
#define AM2_TOK_SUSPENDAI         73
#define AM2_TOK_REVIVEAI          74
#define AM2_TOK_SETCAMERAFOCUS    75
#define AM2_TOK_RESTORECAMERAFOCUS  76
#define AM2_TOK_MOVEITEM          77
#define AM2_TOK_TRIGGER           78
#define AM2_TOK_TRIGGERDELAY      79
#define AM2_TOK_CREATETROOPER     80
#define AM2_TOK_RIFLE             81
#define AM2_TOK_BAZOOKA           82
#define AM2_TOK_GRENADE           83
#define AM2_TOK_FLAMER            84
#define AM2_TOK_MORTAR            85
#define AM2_TOK_AUTORIFLE         86
#define AM2_TOK_FLAK              87
#define AM2_TOK_MINE              88
#define AM2_TOK_YOURS             88
#define AM2_TOK_EXPLOSIVE         89
#define AM2_TOK_DETONATOR         90
#define AM2_TOK_SWEEPER           91
#define AM2_TOK_LURE              92
#define AM2_TOK_VULCAN            93
#define AM2_TOK_HEAVYMG           94
#define AM2_TOK_SNIPER            95
#define AM2_TOK_VEHICLEAMMO       96
#define AM2_TOK_VEHICLEARMOR      97
#define AM2_TOK_VEHICLENITRO      98
#define AM2_TOK_CAMOUFLAGE        99
#define AM2_TOK_DISGUISEGREEN    100
#define AM2_TOK_DISGUISETAN      101
#define AM2_TOK_DISGUISEBLUE     102
#define AM2_TOK_DISGUISEGREY     103
#define AM2_TOK_MAGNIFYING       104
#define AM2_TOK_AEROSOL          105
#define AM2_TOK_M80              106
#define AM2_TOK_MEDPACK          107
#define AM2_TOK_MEDKIT           108
#define AM2_TOK_AIRSTRIKE        109
#define AM2_TOK_PARATROOPERS     110
#define AM2_TOK_RECON            111
#define AM2_TOK_WRENCH           112
#define AM2_TOK_CREATEVEHICLE    113
#define AM2_TOK_CREATEPOWERUP    114
#define AM2_TOK_CREATEEXPLOSION  115
#define AM2_TOK_CREATEROACH      116
#define AM2_TOK_SETFACING        117
#define AM2_TOK_SETGUNFACING     118
#define AM2_TOK_ORDER            119
#define AM2_TOK_FOLLOW           120
#define AM2_TOK_GOTO             121
#define AM2_TOK_INMODE           122
#define AM2_TOK_SETMAXHEALTH     123
#define AM2_TOK_HEAL             124
#define AM2_TOK_DAMAGE           125
#define AM2_TOK_PROJECTILE       126
#define AM2_TOK_FIRE             127
#define AM2_TOK_CRUSH            128
#define AM2_TOK_EXPLOSION        129
#define AM2_TOK_GETDMGLVL        130
#define AM2_TOK_GETHEALTH        131
#define AM2_TOK_GETDISGUISE      132
#define AM2_TOK_VARIABLE         133
#define AM2_TOK_SETVAR           134
#define AM2_TOK_ADDVAR           135
#define AM2_TOK_REFVAR           136
#define AM2_TOK_SETOBJBMP        137
#define AM2_TOK_SETOBJSTATE      138
#define AM2_TOK_OBJECT           139
#define AM2_TOK_OBJCLASS         140
#define AM2_TOK_STATE            141
#define AM2_TOK_FRAME            142
#define AM2_TOK_DEPLOY           143
#define AM2_TOK_UNDEPLOY         144
#define AM2_TOK_RESURRECT        145
#define AM2_TOK_ALLY             146
#define AM2_TOK_UNALLY           147
#define AM2_TOK_SETFORCECOLOR    148
#define AM2_TOK_ACTIVATEREGION   149
#define AM2_TOK_INACTIVATEREGION 150
#define AM2_TOK_SETBRIEFING      151
#define AM2_TOK_SETBRIEFVO       152
#define AM2_TOK_SETSTRATMAP      153
#define AM2_TOK_SETAIMODE        154
#define AM2_TOK_ATTACK           155
#define AM2_TOK_DEFEND           156
#define AM2_TOK_IGNORE           157
#define AM2_TOK_EVADE            158
#define AM2_TOK_SETAIPOSE        159
#define AM2_TOK_STAND            160
#define AM2_TOK_KNEEL            161
#define AM2_TOK_PRONE            162
#define AM2_TOK_NONE             163
#define AM2_TOK_SETSPEED         164
#define AM2_TOK_SLOW             165
#define AM2_TOK_NORMAL           166
#define AM2_TOK_SETNPC           167
#define AM2_TOK_SETM80           168
#define AM2_TOK_SETZOMBIE        169
#define AM2_TOK_SETSCIENTIST     170
#define AM2_TOK_MAKESMOKE        171
#define AM2_TOK_MAKEFLAME        172
#define AM2_TOK_SETITEMFLAG      173
#define AM2_TOK_STRATEGIC        174
#define AM2_TOK_SETITEMOWNER     175
#define AM2_TOK_ADDEXP           176
#define AM2_TOK_FIREWEAPON       177
#define AM2_TOK_UNITFIRE         178
#define AM2_TOK_HASITEM          179
#define AM2_TOK_DROPITEM         180
#define AM2_TOK_ISCOLORINGAME    181
#define AM2_TOK_ISALLY           182
#define AM2_TOK_TEAMSCORE        183
#define AM2_TOK_GROUP            184
#define AM2_TOK_SETUILOCK        185
#define AM2_TOK_SETDAMAGEPAD     186

/* The table itself, in the order ScriptLookupToken walks it -- which matters,
 * because that walk is linear and returns the first match. Two spellings share
 * id 88 and the order decides which of them a reverse lookup reports.
 *
 * Carried here rather than read out of the image. It is the same 185 words
 * docs/scripttokens.md lists, generated from the same array, so the repository
 * gains nothing it did not already hold -- and the reconstruction stops
 * needing the image mapped to answer what a keyword means. The native build,
 * which has no image to read, needs exactly this.
 *
 * tests/selftest.cpp replays every word in the shipped scripts against the
 * ORIGINAL's answers, so a copy that drifted from the binary would fail there
 * rather than in the game.
 */
typedef struct {
    const char *name;
    int32_t     id;
} AM2_ScriptToken;

static const AM2_ScriptToken am2_script_tokens[] = {
    { "(",   1 },
    { ")",   2 },
    { ",",   3 },
    { "<",   4 },
    { "<=",   5 },
    { "=",   6 },
    { ">",   7 },
    { ">=",   8 },
    { "<>",   9 },
    { "{",  10 },
    { "}",  11 },
    { "&",  12 },
    { "+",  13 },
    { "testvar",  14 },
    { "green",  16 },
    { "tan",  17 },
    { "blue",  18 },
    { "grey",  19 },
    { "me",  20 },
    { "army0",  21 },
    { "army1",  22 },
    { "army2",  23 },
    { "army3",  24 },
    { "preloadsprite",  25 },
    { "pad",  26 },
    { "padon",  27 },
    { "padoff",  28 },
    { "everything",  29 },
    { "item",  30 },
    { "sarge",  32 },
    { "unit",  33 },
    { "trooper",  34 },
    { "vehicle",  36 },
    { "tank",  35 },
    { "jeep",  37 },
    { "halftrack",  38 },
    { "convoy",  39 },
    { "boat",  40 },
    { "groundvehicle",  41 },
    { "npc",  42 },
    { "delay",  43 },
    { "if",  44 },
    { "then",  45 },
    { "allof",  46 },
    { "repeat",  49 },
    { "count",  50 },
    { "of",  51 },
    { "butnot",  47 },
    { "inorder",  48 },
    { "after",  52 },
    { "and",  53 },
    { "sequential",  54 },
    { "random",  55 },
    { "onobjstate",  56 },
    { "killed",  57 },
    { "hit",  58 },
    { "healed",  59 },
    { "by",  60 },
    { "pickedup",  61 },
    { "dropped",  62 },
    { "timeabsolute",  63 },
    { "showmessage",  64 },
    { "showbitmap",  65 },
    { "showbitmapnopause",  66 },
    { "playsound",  67 },
    { "playitemsound",  68 },
    { "playmusic",  69 },
    { "tracevar",  70 },
    { "suspendai",  73 },
    { "reviveai",  74 },
    { "setcamerafocus",  75 },
    { "restorecamerafocus",  76 },
    { "moveitem",  77 },
    { "trigger",  78 },
    { "triggerdelay",  79 },
    { "createtrooper",  80 },
    { "rifle",  81 },
    { "bazooka",  82 },
    { "grenade",  83 },
    { "flamer",  84 },
    { "mortar",  85 },
    { "autorifle",  86 },
    { "flak",  87 },
    { "mine",  88 },
    { "yours",  88 },
    { "explosive",  89 },
    { "detonator",  90 },
    { "sweeper",  91 },
    { "lure",  92 },
    { "medpack", 107 },
    { "medkit", 108 },
    { "vulcan",  93 },
    { "heavymg",  94 },
    { "sniper",  95 },
    { "vehicleammo",  96 },
    { "vehiclearmor",  97 },
    { "vehiclenitro",  98 },
    { "camouflage",  99 },
    { "disguisegreen", 100 },
    { "disguisetan", 101 },
    { "disguiseblue", 102 },
    { "disguisegrey", 103 },
    { "magnifying", 104 },
    { "aerosol", 105 },
    { "m80", 106 },
    { "wrench", 112 },
    { "airstrike", 109 },
    { "paratroopers", 110 },
    { "recon", 111 },
    { "createvehicle", 113 },
    { "createpowerup", 114 },
    { "createexplosion", 115 },
    { "createroach", 116 },
    { "setfacing", 117 },
    { "setgunfacing", 118 },
    { "order", 119 },
    { "follow", 120 },
    { "goto", 121 },
    { "inmode", 122 },
    { "deploy", 143 },
    { "undeploy", 144 },
    { "resurrect", 145 },
    { "ally", 146 },
    { "unally", 147 },
    { "setforcecolor", 148 },
    { "setmaxhealth", 123 },
    { "heal", 124 },
    { "damage", 125 },
    { "projectile", 126 },
    { "fire", 127 },
    { "crush", 128 },
    { "explosion", 129 },
    { "getdmglvl", 130 },
    { "gethealth", 131 },
    { "getdisguise", 132 },
    { "variable", 133 },
    { "setvar", 134 },
    { "addvar", 135 },
    { "refvar", 136 },
    { "setobjbmp", 137 },
    { "setobjstate", 138 },
    { "object", 139 },
    { "objclass", 140 },
    { "state", 141 },
    { "frame", 142 },
    { "activateregion", 149 },
    { "inactivateregion", 150 },
    { "setbriefing", 151 },
    { "setbriefvo", 152 },
    { "setstratmap", 153 },
    { "showfailure",  71 },
    { "showpda",  72 },
    { "setaimode", 154 },
    { "attack", 155 },
    { "defend", 156 },
    { "ignore", 157 },
    { "evade", 158 },
    { "setaipose", 159 },
    { "stand", 160 },
    { "kneel", 161 },
    { "prone", 162 },
    { "none", 163 },
    { "setspeed", 164 },
    { "slow", 165 },
    { "normal", 166 },
    { "setnpc", 167 },
    { "setm80", 168 },
    { "setzombie", 169 },
    { "setscientist", 170 },
    { "makesmoke", 171 },
    { "makeflame", 172 },
    { "setitemflag", 173 },
    { "strategic", 174 },
    { "setitemowner", 175 },
    { "addexp", 176 },
    { "fireweapon", 177 },
    { "unitfire", 178 },
    { "setuilock", 185 },
    { "setdamagepad", 186 },
    { "hasitem", 179 },
    { "dropitem", 180 },
    { "iscoloringame", 181 },
    { "isally", 182 },
    { "teamscore", 183 },
    { "group", 184 },
};

#define AM2_SCRIPT_TOKEN_COUNT ((int32_t)(sizeof am2_script_tokens / sizeof am2_script_tokens[0]))

#endif /* AM2_SCRIPTTOKENS_H */
