/* Generated by tools/callsites.py -- do not edit.
 *
 * Direct `call rel32` sites for each observed function. Indirect
 * calls through function pointers and vtables are NOT listed and
 * will not be observed.
 */

#ifndef AM2_SITES_H
#define AM2_SITES_H

#include <stdint.h>

/* 0x004465e0 -- 1 direct call site(s) */
static const uint32_t sites_004465e0[] = {
    0x004467A8,
};

#endif /* AM2_SITES_H */
