/* Generated by tools/callsites.py -- do not edit.
 *
 * Direct `call rel32` sites for each observed function. Indirect
 * calls through function pointers and vtables are NOT listed and
 * will not be observed.
 */

#ifndef AM2_SITES_H
#define AM2_SITES_H

#include <stdint.h>

/* 0x00446930 -- 34 direct call site(s) */
static const uint32_t sites_00446930[] = {
    0x004146E1, 0x00415705, 0x00416568, 0x0041658D, 0x004165B2, 0x004165DA,
    0x004165FF, 0x00416624, 0x0041664C, 0x00416671, 0x00416771, 0x004167BA,
    0x004167E9, 0x00416811, 0x0041685A, 0x00416882, 0x004168CC, 0x0041693A,
    0x0041695F, 0x00416987, 0x004169E3, 0x00416ACE, 0x00416AF2, 0x00416B3A,
    0x00416B5F, 0x00416B9D, 0x00416BC2, 0x00416C01, 0x00416C28, 0x00416C85,
    0x00418AC7, 0x00418B1E, 0x00462878, 0x004628F1,
};

/* 0x0041c710 -- 3 direct call site(s) */
static const uint32_t sites_0041c710[] = {
    0x00446A76, 0x00446C1D, 0x00446DC4,
};

/* 0x00445ff0 -- 24 direct call site(s) */
static const uint32_t sites_00445ff0[] = {
    0x00408EB9, 0x004091AC, 0x0040938E, 0x0041269B, 0x004126BB, 0x0041275C,
    0x0041277D, 0x004131DB, 0x004132F8, 0x00413359, 0x004133BA, 0x004133DF,
    0x00424C88, 0x004254AA, 0x00425C90, 0x00425D80, 0x00425E2F, 0x00426A6E,
    0x00426A7E, 0x00462187, 0x00462754, 0x0046279A, 0x004627C1, 0x00462801,
};

/* 0x00446ab0 -- 11 direct call site(s) */
static const uint32_t sites_00446ab0[] = {
    0x00418F05, 0x00432C2A, 0x00433450, 0x0045495C, 0x00454DFB, 0x00454F7A,
    0x00455310, 0x00456A69, 0x00456AFC, 0x00462963, 0x00462A1C,
};

#endif /* AM2_SITES_H */
