/* Generated by tools/callsites.py -- do not edit.
 *
 * Direct `call rel32` sites for each observed function. Indirect
 * calls through function pointers and vtables are NOT listed and
 * will not be observed.
 */

#ifndef AM2_SITES_H
#define AM2_SITES_H

#include <stdint.h>

/* 0x0041c2b0 -- 2 direct call site(s) */
static const uint32_t sites_0041c2b0[] = {
    0x00446114, 0x004461A6,
};

#endif /* AM2_SITES_H */
