"""Emit the exact direct call sites of a function, for call-site interposition.

Replacing a function needs only its address. *Observing* one without replacing
it needs every place it is called from: we rewrite the rel32 of each
`call target` so it reaches a logging stub instead, and the stub jumps on to the
untouched original. Because the function body is never modified, this needs no
trampoline and no length-disassembler.

The addresses are resolved here, offline and exactly, rather than by scanning
for byte patterns at runtime -- `E8` bytes occur constantly inside longer
instructions and in data, and a false positive would corrupt the image.

    ./.venv/bin/python tools/callsites.py 0x0040c040 0x0042e1c0 > src/inject/sites.h
"""

import os
import sys

import capstone

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import am2

OP_IMM = capstone.x86.X86_OP_IMM


def main(argv):
    if not argv:
        sys.exit("usage: callsites.py <addr> [addr ...]")

    wanted = [int(a, 0) for a in argv]
    img = am2.Image()
    insns = img.disasm(".text")

    found = {va: [] for va in wanted}
    for insn in insns:
        if insn.mnemonic != "call" or not insn.operands:
            continue
        op = insn.operands[0]
        # Only 5-byte `call rel32` (E8) can be retargeted by rewriting rel32.
        if op.type == OP_IMM and op.imm in found and insn.size == 5 \
                and insn.bytes[0] == 0xE8:
            found[op.imm].append(insn.address)

    out = sys.stdout
    out.write("/* Generated by tools/callsites.py -- do not edit.\n"
              " *\n"
              " * Direct `call rel32` sites for each observed function. Indirect\n"
              " * calls through function pointers and vtables are NOT listed and\n"
              " * will not be observed.\n"
              " */\n\n"
              "#ifndef AM2_SITES_H\n#define AM2_SITES_H\n\n"
              "#include <stdint.h>\n\n")

    for va in wanted:
        sites = found[va]
        name = f"sites_{va:08x}"
        out.write(f"/* {va:#010x} -- {len(sites)} direct call site(s) */\n")
        out.write(f"static const uint32_t {name}[] = {{\n")
        for i in range(0, len(sites), 6):
            row = ", ".join(f"0x{s:08X}" for s in sites[i:i + 6])
            out.write(f"    {row},\n")
        out.write("};\n\n")
        print(f"{va:#010x}: {len(sites)} direct call sites", file=sys.stderr)

    out.write("#endif /* AM2_SITES_H */\n")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
