"""Find the copy-protection checks, and say which ones were patched out.

Army Men II checks for its CD in five places. Every one of them compiles to the
same three instructions:

    call FindGameCD          ; 0x00426B50, answers non-zero when the CD is there
    test eax, eax
    jne  <carry on>          ; 75 xx -- and fall through to the MessageBox

In the GOG build every one of those `jne`s is an unconditional `jmp`: the byte
is EB where it must have been 75. One byte per site, five sites, and the effect
is that the check always succeeds and the "The ARMYMEN2 CD must be in the drive"
dialog can never appear. The `test` is left behind setting flags nobody reads,
which is the tell -- no compiler emits that.

So the reconstruction inherits a cracked binary. That is worth writing down
rather than silently reproducing, because "there is no copy protection here" and
"the copy protection was disabled" are different statements about the original,
and only the second one is true.

This regenerates docs/copyprotection.md, which carries the original instruction
for each site so it can be put back. src/game/cdcheck.h holds the same thing as
compilable source behind #ifdef AM2_COPY_PROTECTION.

Nothing here modifies the executable. It reports.
"""

import os
import struct
import sys

import capstone

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import am2

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(REPO, "docs", "copyprotection.md")

FIND_GAME_CD = 0x00426B50

# 75 = jne rel8, the conditional this must have been. EB = jmp rel8, what is
# there now. Same length, so the patch is one byte and nothing moved.
JNE_REL8 = 0x75
JMP_REL8 = 0xEB


def find_sites(img):
    """Every `call FindGameCD` in .text, with the two instructions after it."""
    md = capstone.Cs(capstone.CS_ARCH_X86, capstone.CS_MODE_32)
    _n, start, _end, data = img.section(".text")
    out = []

    for j in range(len(data) - 5):
        if data[j] != 0xE8:
            continue
        if start + j + 5 + struct.unpack_from("<i", data, j + 1)[0] != FIND_GAME_CD:
            continue
        addr = start + j
        # Decode from the call so the following instructions land on real
        # boundaries -- scanning raw bytes for a jump opcode finds the middle of
        # `mov edi, [eax+0x60]` and reports it as `js`.
        insns = list(md.disasm(bytes(data[j:j + 16]), addr))[:3]
        if len(insns) < 3:
            continue
        call, test, jump = insns
        if test.mnemonic != "test":
            continue          # not a checked call; a caller that ignores it
        out.append({
            "call": addr,
            "test": test.address,
            "jump": jump.address,
            "opcode": data[j + 5 + test.size],
            "mnemonic": jump.mnemonic,
            "target": jump.op_str,
            "size": jump.size,
        })
    return out


def main():
    img = am2.Image()
    sites = find_sites(img)
    patched = [s for s in sites if s["opcode"] == JMP_REL8]

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as fh:
        w = fh.write
        w("# The copy protection, and the fact that it is disabled\n\n")
        w("Generated by `tools/cdchecks.py`. Do not edit.\n\n")
        w("`FindGameCD` (`0x00426B50`) answers non-zero when the ARMYMEN2 CD is\n"
          "in a drive. It is called from five places, and each caller tests the\n"
          "result and branches past a `MessageBoxA` that says the CD is\n"
          "required.\n\n")
        w(f"**{len(patched)} of the {len(sites)}** are unconditional in this\n"
          "executable. The byte at the jump is `EB` (`jmp`)\n"
          "where a `75` (`jne`) has to have been: same length, so nothing moved,\n"
          "and the `test` in front of it is left setting flags that nothing\n"
          "reads. No compiler emits a `test` whose flags are dead followed by an\n"
          "unconditional jump, so this is a patch and not a build option.\n\n")
        w("The consequence is that every one of those `MessageBoxA` calls is\n"
          "unreachable. They still count as import sites, which is why\n"
          "`docs/boundary.md` has to say whether a site can actually execute\n"
          "before calling it outstanding work.\n\n")

        w("| call site | jump | now | retail | restore with |\n")
        w("|---|---|---|---|---|\n")
        for s in sites:
            now = f"`{s['mnemonic']} {s['target']}`"
            was = "`jne " + s["target"] + "`" if s["opcode"] == JMP_REL8 else now
            fix = (f"`{s['jump']:#010x}: EB -> 75`"
                   if s["opcode"] == JMP_REL8 else "— not patched")
            w(f"| `{s['call']:#010x}` | `{s['jump']:#010x}` | {now} | {was} | {fix} |\n")
        w("\n")

        w("## Putting it back\n\n")
        w("Each is a single byte, in place, no relocation:\n\n```\n")
        for s in patched:
            w(f"{s['jump']:#010x}  EB -> 75\n")
        w("```\n\n")
        w("`src/game/cdcheck.h` carries the same thing as source: the check the\n"
          "retail build performed, written out behind `#ifdef\n"
          "AM2_COPY_PROTECTION` so it is recorded and compiles, but is not built\n"
          "by default -- the port matches the binary it is derived from.\n\n")
        w("Do not turn it on expecting the game to then demand a CD. All five\n"
          "call sites are in menu functions that are still the original's code,\n"
          "so nothing calls the restored check yet and the patched bytes would\n"
          "keep letting everyone through regardless.\n\n")
        w("It is also deliberately not built by default for a second reason. The\n"
          "port is verified by running the original and the reconstruction side\n"
          "by side and comparing (`tools/ab.sh`); a reconstructed menu function\n"
          "that demanded a CD where the original's does not would diverge on\n"
          "every such comparison, for a reason having nothing to do with whether\n"
          "the reconstruction is correct.\n")

    print(f"-> {os.path.relpath(OUT, REPO)}")
    print(f"{len(sites)} CD checks, {len(patched)} patched to unconditional")
    for s in patched:
        print(f"  {s['call']:#010x} -> jump at {s['jump']:#010x}  EB should be 75")


if __name__ == "__main__":
    main()
