"""Dump the cheat table out of the image, into docs/cheats.md.

The cheat handler at 0x00417B80 matches a typed line against a table of phrase
pointers at 0x00476708 and dispatches through a 39-entry jump table at
0x004183E4. The phrases are the GAME'S OWN vocabulary -- like the script
keywords tools/scripttokens.py recovers -- so they are read out of the binary
rather than typed here, for the same reason: a hand-copied list of thirty-nine
strings is thirty-nine chances to be wrong and nothing would check it.

WHY IT MATTERS BEYOND THE LIST. The arms are NOT laid out in dispatch order:
entry 31, "god of gamblers", sits at 0x00417C3A, which is BEFORE the jump
itself and ahead of entry 0. Reading the bodies from the top and numbering as
you go gives "santini" the wrong one -- the failure DirtyCollect's eighty-one
arms and WeaponClassOf's four both record, here at thirty-nine-way scale. The
switch has to be generated from this, not transcribed.

The bound is the loop's rather than a guess: it walks p = 0x00476708 while
p < 0x004767A4, which is thirty-nine entries, and refuses an index above 0x26.

    tools/cheats.py            regenerate docs/cheats.md
"""

import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import am2

PHRASES = 0x00476708
PHRASES_END = 0x004767A4
JUMPS = 0x004183E4


def main():
    img = am2.Image()
    n = (PHRASES_END - PHRASES) // 4
    rows = []
    for i in range(n):
        p = int.from_bytes(img.read(PHRASES + i * 4, 4), "little")
        t = int.from_bytes(img.read(JUMPS + i * 4, 4), "little")
        rows.append((i, img.cstring(p), t))

    first = min(range(n), key=lambda i: rows[i][2])
    out = ["# The cheat table", "",
           "Generated by `tools/cheats.py` from the image; do not edit.", "",
           "`0x00417B80` compares the typed line against each phrase in turn and",
           "jumps through the table at `0x%08X`. %d phrases, %d distinct arms."
           % (JUMPS, n, len(set(r[2] for r in rows))), "",
           "The arms are **not** laid out in dispatch order: entry %d is at "
           "`0x%08X`," % (first, rows[first][2]),
           "ahead of entry 0 and of the jump itself. Generated rather than read",
           "off the bodies for that reason.", "",
           "| # | phrase | arm |", "|---:|---|---|"]
    for i, s, t in rows:
        out.append("| %d | `%s` | `0x%08X` |" % (i, s, t))
    out.append("")
    with open(os.path.join(HERE, "..", "docs", "cheats.md"), "w") as f:
        f.write("\n".join(out))
    print("docs/cheats.md: %d phrases, %d arms"
          % (n, len(set(r[2] for r in rows))))
    return 0


if __name__ == "__main__":
    sys.exit(main())
