#!/usr/bin/env python3
"""Run the ORIGINAL dirty-rectangle list through a sequence of appends.

This exists because nothing else can check it. AddDirtyRect runs 618 times in
live play and ZERO at the briefing, so `ab.sh bootcamp` cannot see it at all --
measured, by never linking a record and watching the run stay at its usual 22
pixels. `ab.sh mission` does execute it and still cannot see it, because its
shot is of a settled scene where every stale region has been painted over; the
same mutation comes out at 293, inside the band clean runs give.

So this is the third kind of oracle in this tree, after tools/scriptcheck.py's
corpus and tools/placecheck.py's: a STATEFUL one. The function's answer is not
a return value, it is the array afterwards -- so the recording is the array,
and the sequence that produced it is part of the vector.

Nothing about the game runs. The records and the three globals beside them are
.bss, which the offline test maps as it maps everything else, and the function
touches nothing but them.
"""
import os
import struct
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import am2
from vectors import Emu, STACK, STACK_SZ, RET_MAGIC
from unicorn import UcError
from unicorn.x86_const import UC_X86_REG_EIP, UC_X86_REG_ESP

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "tests/dirtyvec.h")

ADDR_RESET_DIRTY_LIST = 0x0041DCE0
ADDR_ADD_DIRTY_RECT = 0x0041DD00
ADDR_DIRTY_RECTS = 0x00508AC4
ADDR_DIRTY_TAIL = 0x00508AC0
ADDR_FULL_REDRAW = 0x00512460
AM2_DEPTH_MAX = 0x1F4
RECORD_SIZE = 20

# The whole array plus the tail that precedes it, so the dump is one span.
REGION = ADDR_DIRTY_TAIL
REGION_LEN = 4 + AM2_DEPTH_MAX * RECORD_SIZE


def rects(n):
    """A rectangle per step, each distinguishable from every other.

    Deliberately not random: the point of a stateful vector is that the whole
    sequence is the input, so it has to be written down, and a formula is
    shorter than 520 rows of numbers. Negatives and a zero-area box are in
    there because the function does no validation at all and a reconstruction
    that added some would pass a corpus of sensible rectangles.
    """
    out = []
    for i in range(n):
        l = (i * 37) % 640 - 64
        t = (i * 53) % 480 - 32
        out.append((l, t, l + (i % 7), t + (i % 5)))
    return out


def seed():
    """The state the sequence starts from, and it is NOT zeros.

    It was zeros, and that made one store untestable: ResetDirtyList clears
    three fields, and clearing something already zero cannot be observed.
    Deleting its third store passed all eight sequences. The same trap as
    ScriptVariable's duplicate-name check, which a corpus of empty tables
    could not reach -- ask what state a check needs before believing it is
    covered.

    ADDR_FULL_REDRAW is seeded too, with a value neither function writes, so
    a reconstruction that cleared it would be caught as well.
    """
    return bytes(((i * 7 + 13) & 0xFF) for i in range(REGION_LEN))


class Runner:
    def __init__(self):
        self.emu = Emu()

    def call(self, addr, args):
        uc = self.emu.uc
        sp = STACK + STACK_SZ - 0x2000
        for a in reversed(args):
            sp -= 4
            uc.mem_write(sp, struct.pack("<i", a))
        sp -= 4
        uc.mem_write(sp, struct.pack("<I", RET_MAGIC))
        uc.reg_write(UC_X86_REG_ESP, sp)
        uc.emu_start(addr, RET_MAGIC, timeout=5000000, count=100000)
        if uc.reg_read(UC_X86_REG_EIP) != RET_MAGIC:
            raise RuntimeError("no return from 0x%08x" % addr)

    def run(self, n):
        uc = self.emu.uc
        uc.mem_write(REGION, seed())
        uc.mem_write(ADDR_FULL_REDRAW, struct.pack("<I", 0x5A5A5A5A))
        self.call(ADDR_RESET_DIRTY_LIST, [])
        for r in rects(n):
            self.call(ADDR_ADD_DIRTY_RECT, list(r))
        return (bytes(uc.mem_read(REGION, REGION_LEN)),
                struct.unpack("<i", bytes(uc.mem_read(ADDR_FULL_REDRAW, 4)))[0])


# One short sequence, one that fills the array exactly, and one that runs past
# the end -- the overflow arm is half the function and no shipped frame is
# going to reach it on demand.
LENGTHS = [0, 1, 2, 17, AM2_DEPTH_MAX - 2, AM2_DEPTH_MAX - 1,
           AM2_DEPTH_MAX, AM2_DEPTH_MAX + 40]


def main():
    runner = Runner()
    rows = []
    for n in LENGTHS:
        region, full = runner.run(n)
        rows.append((n, full, region))

    with open(OUT, "w") as fh:
        fh.write("/* Generated by tools/dirtycheck.py -- do not edit.\n"
                 " *\n"
                 " * One row per sequence length. `region` is the tail index\n"
                 " * followed by the whole 500-record array, exactly as the\n"
                 " * ORIGINAL left it, and `full` is ADDR_FULL_REDRAW. The\n"
                 " * rectangles are generated -- see rects() in the tool, and\n"
                 " * the same formula in tests/selftest.cpp.\n"
                 " */\n")
        fh.write("#define AM2_DIRTY_REGION_LEN %d\n\n" % REGION_LEN)
        fh.write("typedef struct { int32_t adds; int32_t full;\n"
                 "                 unsigned char region[AM2_DIRTY_REGION_LEN];\n"
                 "               } AM2_DirtyVector;\n\n")
        fh.write("static const AM2_DirtyVector am2_dirty_vectors[] = {\n")
        for n, full, region in rows:
            body = ",".join("0x%02x" % b for b in region)
            fh.write("  { %d, %d, {%s} },\n" % (n, full, body))
        fh.write("};\n")

    print("%d sequences, %d bytes of state each"
          % (len(rows), REGION_LEN))
    for n, full, region in rows:
        live = sum(1 for i in range(AM2_DEPTH_MAX)
                   if region[4 + i * RECORD_SIZE + 0x12] or i == 0)
        print("  %4d adds -> tail %3d, full=%d, %d record(s) with a next"
              % (n, struct.unpack("<H", region[:2])[0], full, live))


if __name__ == "__main__":
    main()
