#!/usr/bin/env python3
"""Fold code-read blob strings to inline C literals, by macro redirect.

A handful of strings are still read out of the carried blob by the
reconstruction -- CRT import names and runtime-error banners, the CD-required
message, the multiplayer status/log lines, the team-win event names, the
bad-map/rules panel messages. Each is used ONLY as a string (never as an
address: a loop bound like ADDR_OPTION_TABLE_END, which shares this shape, is
deliberately NOT here). Redirecting the macro to a C literal in the native/SA
build makes those reads hit the binary's own .rodata, and the blob's copies go
dead -- tools/deadstrings.py then drops them (it excludes these VAs from its
"coded" keep via folded_vas()).

Safe because in the native build AM2_IMAGE(a) == a (am2_image_slide is 0), so
`STR(x)`/`AM2_IMAGE(x)` on a literal address yields the literal. The hybrid,
which maps the image elsewhere, does not take these redirects (they are under
AM2_STANDALONE).

Emits build/standalone/foldstr.h, included by src/inject/standalone.h. Runs in
standalone-generate before deadstrings. Asserts every literal round-trips to the
exact image bytes, so a wrong transcription fails the build, not a play test.
"""
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import am2

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(REPO, "build", "standalone")

# Vetted string-only macros (tools context-analysis + spot check). NOT any
# macro used as an address (comparisons, loop bounds, pointer arithmetic).
FOLD = [
    "STR_KERNEL32", "STR_USER32", "STR_MESSAGEBOXA",
    "STR_GETLASTACTIVEPOPUP", "STR_GETACTIVEWINDOW",
    "STR_RTERR_CAPTION", "STR_RTERR_BANNER", "STR_RTERR_NONAME",
    "CRT_EXPONENT_TEXT",
    "STR_REMOTE_ACKING_X", "STR_REMOTE_ACKING_D",
    "STR_CAPS_GUAR_YES", "STR_CAPS_GUAR_NO",
    "STR_LOBBY_AS_HOST", "STR_LOBBY_AS_SLAVE",
    "CD_REQUIRED_TEXT", "CD_REQUIRED_CAPTION",
    "STR_TRUE", "STR_FALSE",
    "STR_BOOL_TRUE_CAP", "STR_BOOL_TRUE_LOW",
    "STR_BOOL_FALSE_CAP", "STR_BOOL_FALSE_LOW",
    "NAME_GREENWINS", "NAME_TANWINS", "NAME_BLUEWINS", "NAME_GREYWINS",
    "NAME_GREENTEAMWINS", "NAME_TANTEAMWINS", "NAME_BLUETEAMWINS",
    "NAME_GREYTEAMWINS",
    "MSG_BAD_MAP", "MSG_BAD_RULES", "MSG_BAD_INSTALL",
    "MSG_NO_MAP", "MSG_NO_RULES",
]


def _c_literal(s):
    out = '"'
    for ch in s:
        if ch == "\\":
            out += "\\\\"
        elif ch == '"':
            out += '\\"'
        elif ch == "\n":
            out += "\\n"
        elif ch == "\t":
            out += "\\t"
        elif ch == "\r":
            out += "\\r"
        elif 32 <= ord(ch) < 127:
            out += ch
        else:
            out += "\\x%02x" % ord(ch)
    return out + '"'


def _unescape(lit):
    return bytes(lit[1:-1], "latin-1").decode("unicode_escape").encode("latin-1")


def entries():
    """[(macro, va, image_string)] for the fold list, resolved from orig.h."""
    oh = open(os.path.join(REPO, "src", "inject", "orig.h")).read()
    img = am2.Image()
    out = []
    for name in FOLD:
        m = re.search(r'#define\s+ADDR_' + name + r'\s+0x([0-9A-Fa-f]+)u', oh)
        if not m:
            raise SystemExit("foldstrings: no ADDR_%s in orig.h" % name)
        va = int(m.group(1), 16)
        s = img.cstring(va)
        if s is None:
            raise SystemExit("foldstrings: 0x%08X (%s) is not a string" % (va, name))
        out.append((name, va, s))
    return out


def folded_vas():
    return {va for _name, va, _s in entries()}


def main():
    os.makedirs(OUT, exist_ok=True)
    lines = ["/* Generated by tools/foldstrings.py -- do not edit. */",
             "#ifndef AM2_FOLDSTR_H", "#define AM2_FOLDSTR_H", ""]
    for name, va, s in entries():
        lit = _c_literal(s)
        assert _unescape(lit) == s.encode("latin-1"), (name, lit)
        lines.append("#undef ADDR_%s" % name)
        lines.append("#define ADDR_%s ((uintptr_t)(const char *)%s)" % (name, lit))
    lines += ["", "#endif", ""]
    open(os.path.join(OUT, "foldstr.h"), "w").write("\n".join(lines))
    print("foldstrings: folded %d strings to literals" % len(FOLD))


if __name__ == "__main__":
    main()
