#!/usr/bin/env python3
"""Generate the data image the standalone build places at the original's VAs.

THE STANDALONE BUILD is an EXE that replaces ArmyMen2.exe in the game folder,
needing the original at BUILD time only.  None of the original's CODE is
required -- measured: of the 1,685 `.text` addresses src/game names, 1,640
are `patch_replace` targets a standalone build has nothing to detour, and the
other 46 are the CRT, rand and log seams that become libc.

WHY THE DATA KEEPS THE ORIGINAL'S ADDRESSES, having first been generated as
1,363 separate C objects.  That version linked and ran and faulted before its
first log line, and the reason is a fact about this image rather than a bug:
its RELOCATIONS ARE STRIPPED, and its .rdata and .data hold 3,582 dwords that
look like pointers into .rdata/.data.  Some are -- 0x004702C0 -> 0x004702D8,
and a run of them at 0x18 intervals.  Some are not: 0x00606060 is the ASCII
"```".  Nothing distinguishes them, so moving the data breaks the real ones
and rewriting by pattern corrupts the strings among them.

Placed back at the addresses they were written for, all 3,582 are correct and
none needs touching.  The section is OURS -- the binary depends on no other
file at run time -- it simply occupies the same range, and our own code is
linked above it at 0x00700000.

WHAT STILL NEEDS FIXING UP is the other direction: 408 dwords that are
FUNCTION pointers, the 33 menu vtables among them.  Those are unambiguous,
because a reconstructed function's original address is known exactly, and
they are rewritten at startup to point at ours.  The original's .text is not
present, so a pointer that is missed faults at once rather than running
something unexpected.

THIS IS A STAGE, NOT THE DESTINATION.  Every table carved out of the blob and
written as typed, named C data is one less thing depending on the layout, and
when the last one goes so does the placement constraint.  That is the same
piecewise method the functions were reconstructed by.

    tools/mkglobals.py            # writes build/standalone/
"""
import os
import struct
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import am2
import merges
import checkclaims as cc

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(REPO, "build", "standalone")

BLOB_LO = 0x0046F000          # the original's .rdata
BLOB_HI = 0x00666000          # the end of its .data
SECTION = ".origdat"


def main():
    os.makedirs(OUT, exist_ok=True)
    img = am2.Image()

    blob = bytearray(BLOB_HI - BLOB_LO)
    for s in img.pe.sections:
        name = s.Name.decode().rstrip("\0")
        if name not in (".rdata", ".data"):
            continue
        va = s.VirtualAddress + 0x400000
        raw = img.pe.get_data(s.VirtualAddress, s.SizeOfRawData)
        off = va - BLOB_LO
        blob[off:off + len(raw)] = raw

    binpath = os.path.join(OUT, "origdata.bin")
    open(binpath, "wb").write(bytes(blob))

    with open(os.path.join(OUT, "origdata.S"), "w") as fh:
        fh.write("/* Generated by tools/mkglobals.py -- do not edit.\n"
                 " *\n"
                 " * The original's .rdata and .data, placed by the linker at\n"
                 " * the addresses they were written for.  See the tool's\n"
                 " * docstring for why they cannot simply be moved.\n"
                 " */\n"
                 "    .section %s,\"dw\"\n"
                 "    .globl am2_origdata\n"
                 "am2_origdata:\n"
                 "    .incbin \"%s\"\n" % (SECTION, binpath))

    # The function pointers the original stored in its own data.  A dword
    # equal to a reconstructed function's ORIGINAL address is one; nothing
    # else in this range is unambiguous enough to touch.
    done = set(merges.reconstructed())
    a2n = {}
    for n, a in cc._name_addresses().items():
        a2n.setdefault(int(a, 16), n)

    fixups = []
    for off in range(0, len(blob) - 3, 4):
        v = struct.unpack_from("<I", blob, off)[0]
        if v in done and v in a2n:
            fixups.append((BLOB_LO + off, a2n[v]))

    import glob
    headers = ([os.path.join(REPO, "src/game/win32/widget.h")]
               + sorted(glob.glob(os.path.join(REPO, "src/game/*.h")))
               + sorted(glob.glob(os.path.join(REPO, "src/game/win32/*.h"))))
    with open(os.path.join(OUT, "fixups.cpp"), "w") as fh:
        fh.write("/* Generated by tools/mkglobals.py -- do not edit.\n"
                 " *\n"
                 " * The original stored pointers to its own functions in its\n"
                 " * own data -- the 33 menu vtables among them.  Its code is\n"
                 " * not in this binary, so each is rewritten to ours before\n"
                 " * WinMain runs.\n"
                 " */\n"
                 '#include "%s/src/inject/win32.h"\n' % REPO)
        for h in headers:
            fh.write('#include "%s"\n' % h)
        fh.write("\n#include <stdint.h>\n\n"
                 'extern "C" void am2_apply_fixups(void);\n\n'
                 "void am2_apply_fixups(void)\n{\n")
        for addr, fn in fixups:
            fh.write("    *(const void **)(uintptr_t)0x%08Xu = "
                     "(const void *)%s;\n" % (addr, fn))
        fh.write("}\n")

    print("mkglobals:")
    print("  %s  0x%06X..0x%06X  %d bytes"
          % (SECTION, BLOB_LO, BLOB_HI, len(blob)))
    print("  function-pointer fixups : %d" % len(fixups))
    print("  written to              : build/standalone/")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
