#!/usr/bin/env python3
"""Run the ORIGINAL `place` line parser over every line the game ships.

Same argument as tools/scriptcheck.py: where the program supplies its own
input, use that instead of synthetic vectors. Thirty-six `*_place.txt` files
ship under the multiplayer map directories, and every one of their lines is a
`place` statement -- a real corpus for a parser whose whole job is to turn six
text columns into a 0x30-byte record.

Nothing about the game runs. The parser reaches strtok, DefParseNumber and the
unit-type name table, all of which live in the mapped image, so it is entirely
self-contained under Unicorn. AddPlacement is HOOKED rather than executed: it
reaches the CRT allocator, and the record it would copy is the thing being
measured, so reading it at the call is both cheaper and more direct.

The answers land in tests/placevec.h for tests/selftest.cpp to replay against
the reconstruction. NOT the whole record, though the whole record is recorded:
three padding bytes after `facing` are never written and `name` is filled by a
strcpy, so both hold stack. Unicorn's stack is zero and Wine's is not, which
is how that was noticed -- see the comparison in tests/selftest.cpp.
"""
import os
import struct
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import am2
from vectors import Emu, SCRATCH, STACK, STACK_SZ, RET_MAGIC
from unicorn import UC_HOOK_CODE, UcError
from unicorn.x86_const import UC_X86_REG_EIP, UC_X86_REG_ESP, UC_X86_REG_EAX

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GAME_DIR = os.path.join(ROOT, ".wine/drive_c/GOG Games/Army Men II")
OUT = os.path.join(ROOT, "tests/placevec.h")

ADDR_PARSE_PLACE_LINE = 0x0043B490
ADDR_ADD_PLACEMENT = 0x0043B410
PLACE_CMD = 0x63          # the id the .aai keyword table pairs with "place"

LINE_AT = 0x1000          # inside SCRATCH; the parser writes NULs into it
REC_SZ = 0x30


def place_files():
    out = []
    for base, _dirs, names in os.walk(os.path.join(GAME_DIR, "data")):
        for n in sorted(names):
            if n.lower().endswith("_place.txt"):
                out.append(os.path.join(base, n))
    return sorted(out)


def place_lines():
    """Every distinct `place` line, with the file it came from.

    The keyword itself is stripped, because DefDispatchLine has already
    NUL-terminated it and hands the handler only the remainder.
    """
    seen, out = set(), []
    for path in place_files():
        with open(path, "rb") as fh:
            for raw in fh.read().split(b"\n"):
                raw = raw.rstrip(b"\r")
                if not raw or raw.lstrip().startswith(b"#"):
                    continue
                head = raw.split(None, 1)
                if len(head) != 2 or head[0].lower() != b"place":
                    continue
                rest = head[1]
                if rest in seen:
                    continue
                seen.add(rest)
                out.append((os.path.basename(path), rest))
    return out


class Runner:
    def __init__(self):
        self.emu = Emu()
        self.rec = None
        self.emu.uc.hook_add(UC_HOOK_CODE, self._hook)

    def _hook(self, uc, addr, _size, _user):
        if addr != ADDR_ADD_PLACEMENT:
            return
        esp = uc.reg_read(UC_X86_REG_ESP)
        ret, arg = struct.unpack("<2I", bytes(uc.mem_read(esp, 8)))
        self.rec = bytes(uc.mem_read(arg, REC_SZ))
        uc.reg_write(UC_X86_REG_EAX, 0)
        uc.reg_write(UC_X86_REG_EIP, ret)
        uc.reg_write(UC_X86_REG_ESP, esp + 4)

    def run(self, line):
        uc = self.emu.uc
        uc.mem_write(SCRATCH + LINE_AT, line + b"\0")
        self.rec = None
        sp = STACK + STACK_SZ - 0x2000
        for a in reversed((PLACE_CMD, SCRATCH + LINE_AT)):
            sp -= 4
            uc.mem_write(sp, struct.pack("<I", a))
        sp -= 4
        uc.mem_write(sp, struct.pack("<I", RET_MAGIC))
        uc.reg_write(UC_X86_REG_ESP, sp)
        try:
            uc.emu_start(ADDR_PARSE_PLACE_LINE, RET_MAGIC,
                         timeout=5000000, count=4000000)
        except UcError:
            return None, None
        if uc.reg_read(UC_X86_REG_EIP) != RET_MAGIC:
            return None, None
        return uc.reg_read(UC_X86_REG_EAX), self.rec


def main():
    lines = place_lines()
    runner = Runner()
    rows, faults, norec = [], 0, 0
    for name, line in lines:
        rc, rec = runner.run(line)
        if rc is None:
            faults += 1
            continue
        if rec is None:
            norec += 1
            rec = b"\0" * REC_SZ
        rows.append((name, line, rc, rec))

    with open(OUT, "w") as fh:
        fh.write("/* Generated by tools/placecheck.py -- do not edit.\n"
                 " *\n"
                 " * One row per distinct `place` line the game ships, with\n"
                 " * what the ORIGINAL parser at 0x0043B490 returned and the\n"
                 " * 0x30-byte record it handed AddPlacement. `added` is 0\n"
                 " * where the line was rejected before any record was made.\n"
                 " */\n")
        fh.write("typedef struct { const char *line; int32_t rc;\n"
                 "                 int32_t added; unsigned char rec[0x30];\n"
                 "               } AM2_PlaceVector;\n\n")
        fh.write("static const AM2_PlaceVector am2_place_vectors[] = {\n")
        for name, line, rc, rec in rows:
            txt = line.decode("latin1").replace("\\", "\\\\").replace('"', '\\"')
            txt = txt.replace("\t", "\\t")
            added = 0 if rec == b"\0" * REC_SZ else 1
            body = ",".join("0x%02x" % b for b in rec)
            fh.write('  { "%s", %d, %d, {%s} },\n' % (txt, rc, added, body))
        fh.write("};\n")

    print("%d place files, %d distinct lines, %d recorded"
          % (len(place_files()), len(lines), len(rows)))
    if faults:
        print("  %d line(s) faulted under emulation and are NOT recorded"
              % faults)
    if norec:
        print("  %d line(s) parsed without producing a record" % norec)


if __name__ == "__main__":
    main()
