#!/usr/bin/env python3
"""Check crt_qsort and crt_bsearch against the original's, over arrays full of
ties.

MSVC 6's qsort is a quicksort with a median pivot and an explicit stack; the
order it leaves EQUAL keys in is a property of its exact comparisons and
swaps, and the game sorts things it then draws, so that order reaches the
screen. glibc's qsort is a mergesort and leaves ties where they were. This
runs the ORIGINAL at 0x004660B2 under Unicorn with a comparator stub placed
in the scratch page -- `key_a - key_b` over the first dword of each record --
and records what it did to arrays whose keys are drawn from a range small
enough that ties are the rule. Each record carries a tag in its second
dword, so the tie order is visible in the output. bsearch at 0x00466280 is
run over the sorted arrays for every key in range, present or not.

    tools/qsortcheck.py                    # compare against the Python model
    tools/qsortcheck.py --emit tests/qsortvec.h

tests/selftest.cpp replays the emitted rows through the C, so the
transcription is checked as well as the model. CHECKS names the two, since
neither has a counter that can move: nothing patches the CRT.

MUTATION-CHECKED, and one gap is a theorem. Letting shortsort's scan take a
later equal maximum fails 132 rows; making the loguy walk stop at an equal
key fails 141; probing the middle rather than the low middle on an even
count fails 339 of the bsearch rows. Swapping which side of a partition is
pushed and which is recursed into first fails NOTHING, and cannot: the two
ranges are sorted either way and never overlap, so only the depth of the
pending stack changes. That choice is verified by reading (the original
recurses on the smaller side) and by no corpus.
"""
import argparse
import os
import random
import struct
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from vectors import Emu, SCRATCH, SCRATCH_SZ

CHECKS = ("crt_qsort", "crt_bsearch")

QSORT = 0x004660B2
BSEARCH = 0x00466280
WIDTH = 8

# mov eax,[esp+4]; mov ecx,[esp+8]; mov eax,[eax]; sub eax,[ecx]; ret
COMPARE_STUB = bytes.fromhex("8b442404" "8b4c2408" "8b00" "2b01" "c3")
STUB_AT = SCRATCH + 0x7F00
ARRAY_AT = SCRATCH + 0x100


def cases():
    rng = random.Random(0x6A2)
    out = []
    for n in list(range(0, 41)) + [64, 100, 257, 300]:
        for spread in (1, 2, 3, 8):
            keys = [rng.randrange(spread) for _ in range(n)]
            out.append(keys)
    # Runs the cutoff and the pivot see as sorted, reversed and constant.
    for n in (8, 9, 16, 17, 33):
        out.append(list(range(n)))
        out.append(list(range(n, 0, -1)))
        out.append([7] * n)
    return out


def run_original(emu, keys):
    n = len(keys)
    buf = bytearray(SCRATCH_SZ)
    buf[STUB_AT - SCRATCH:STUB_AT - SCRATCH + len(COMPARE_STUB)] = COMPARE_STUB
    for i, k in enumerate(keys):
        struct.pack_into("<ii", buf, ARRAY_AT - SCRATCH + i * WIDTH, k, i)
    _, after = emu.call(QSORT, [ARRAY_AT, n, WIDTH, STUB_AT], bytes(buf), count=60000000)
    if after is None:
        return None, None
    recs = [struct.unpack_from("<ii", after, ARRAY_AT - SCRATCH + i * WIDTH) for i in range(n)]
    # bsearch over the sorted array, every key from -1 to max+1
    found = []
    for k in range(-1, (max(keys) if keys else 0) + 2):
        struct.pack_into("<i", buf, 0, k)
        buf[ARRAY_AT - SCRATCH:ARRAY_AT - SCRATCH + n * WIDTH] = after[ARRAY_AT - SCRATCH:ARRAY_AT - SCRATCH + n * WIDTH]
        eax, _ = emu.call(BSEARCH, [SCRATCH, ARRAY_AT, n, WIDTH, STUB_AT], bytes(buf), count=400000)
        if eax is None:
            return None, None
        found.append((k, -1 if eax == 0 else (eax - ARRAY_AT) // WIDTH))
    return recs, found


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--emit", help="write the C replay table here")
    args = ap.parse_args()
    emu = Emu()
    rows = []
    faults = 0
    for keys in cases():
        recs, found = run_original(emu, keys)
        if recs is None:
            faults += 1
            print("  n=%d: the original FAULTED" % len(keys))
            continue
        rows.append((keys, recs, found))
    total = sum(len(r[1]) for r in rows)
    print("qsortcheck: %d arrays, %d records sorted, %d bsearch probes, %d faults"
          % (len(rows), total, sum(len(r[2]) for r in rows), faults))
    if args.emit:
        lines = ["/* Generated by tools/qsortcheck.py -- do not edit.",
                 " *",
                 " * What the ORIGINAL qsort at 0x004660B2 did to each array of",
                 " * {key, tag} records under a key_a - key_b comparator, and what",
                 " * its bsearch at 0x00466280 answered for every key in range.",
                 " * The tag says where each tie went. */",
                 "typedef struct { int32_t count; int32_t first; int32_t probes; int32_t firstProbe; } AM2_QsortCase;",
                 "static const int32_t am2_qsort_keys[] = {"]
        keys_flat, out_flat, probe_flat, case_lines = [], [], [], []
        for keys, recs, found in rows:
            case_lines.append("    { %d, %d, %d, %d }," % (len(keys), len(keys_flat), len(found), len(probe_flat) // 2))
            keys_flat += keys
            for k, t in recs:
                out_flat += [k, t]
            for k, idx in found:
                probe_flat += [k, idx]
        def emit_list(name, vals, per=16):
            out = ["static const int32_t %s[] = {" % name]
            for i in range(0, max(len(vals), 1), per):
                out.append("    " + ", ".join(str(v) for v in (vals[i:i + per] or [0])) + ",")
            out.append("};")
            return out
        lines = lines[:-1] + emit_list("am2_qsort_keys", keys_flat) \
            + emit_list("am2_qsort_sorted", out_flat) \
            + emit_list("am2_bsearch_probes", probe_flat) \
            + ["static const AM2_QsortCase am2_qsort_cases[] = {"] + case_lines + ["};"]
        text = "\n".join(lines) + "\n"
        if not (os.path.exists(args.emit) and open(args.emit).read() == text):
            open(args.emit, "w").write(text)
        print("emitted %s" % args.emit)
    return 1 if faults else 0


if __name__ == "__main__":
    sys.exit(main())
