#!/usr/bin/env python3
"""The action vocabulary of the script interpreter, read out of its tables.

ScriptParseAction (0x00440D70) dispatches on a byte-index table over keyword
ids 64..186, and four of its arms dispatch again on a nested table -- weapons
for `createtrooper`, chassis for `createvehicle`, pickups for `createpowerup`,
and damage kinds for `damage` and `setdamagepad`. Reading those tables is the
only way to see the whole language; the arms themselves are 8,608 bytes of
near-identical operand parsing.

Bounds come from the code, never from a guess -- the same rule that turned up
44 missing keywords when the token table's range was assumed.
"""
import os
import re
import struct
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import am2

try:
    import capstone
except ImportError:
    sys.exit("capstone is required")

ACTION_FN = 0x00440D70
ACTION_SIZE = 8608
OUTER_BYTES = 0x00442D6C        # byte index table, ids 0x40..0xBA
OUTER_JUMPS = 0x00442C7C
OUT = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                   "docs/scriptactions.md")


def keywords(img):
    out = {}
    for k in range((0x00488258 - 0x00487C90) // 8):
        p, v = struct.unpack_from("<II", img.read(0x00487C90 + k * 8, 8), 0)
        out[v] = img.cstring(p)
    return out


def outer(img):
    bt = img.read(OUTER_BYTES, 0x7B)
    jt = struct.unpack("<%dI" % (max(bt) + 1),
                       img.read(OUTER_JUMPS, 4 * (max(bt) + 1)))
    groups = {}
    for i, b in enumerate(bt):
        groups.setdefault(jt[b], []).append(0x40 + i)
    return groups


def nested(img):
    """Every `jmp [reg*4 + table]` inside the function that is not the outer
    one, with the id range the compare in front of it establishes."""
    md = capstone.Cs(capstone.CS_ARCH_X86, capstone.CS_MODE_32)
    ins = list(md.disasm(img.read(ACTION_FN, ACTION_SIZE), ACTION_FN))
    found = []
    for k, i in enumerate(ins):
        if i.mnemonic != "jmp" or "*4 + " not in i.op_str:
            continue
        m = re.search(r"\*4 \+ (0x[0-9a-f]+)", i.op_str)
        if not m or int(m.group(1), 16) == OUTER_JUMPS:
            continue
        table = int(m.group(1), 16)
        base = lim = None
        for c in ins[max(0, k - 8):k]:
            mm = re.match(r"e[a-z]x, -(0x[0-9a-f]+|\d+)$", c.op_str)
            if c.mnemonic == "add" and mm:
                base = int(mm.group(1), 0)
            if c.mnemonic == "cmp" and re.match(r"e[a-z]x, (0x[0-9a-f]+|\d+)$",
                                                c.op_str):
                lim = int(c.op_str.split(", ")[1], 0)
        if base is None or lim is None:
            continue
        arms = struct.unpack("<%dI" % (lim + 1), img.read(table, 4 * (lim + 1)))
        found.append((i.address, base, arms))
    return found


def main():
    img = am2.Image()
    kw = keywords(img)
    groups = outer(img)

    rows = []
    for arm, ids in groups.items():
        if len(ids) > 4:
            continue                    # the shared default
        rows.append((min(ids), arm, ids))
    rows.sort()

    seen = set()
    blocks = []
    for addr, base, arms in nested(img):
        key = (base, arms)
        if key in seen:
            continue
        seen.add(key)
        blocks.append((addr, base, arms))

    with open(OUT, "w") as fh:
        fh.write("# Script actions\n\n")
        fh.write("Generated by `tools/scriptactions.py`. The keywords "
                 "`ScriptParseAction` accepts, from the dispatch table at "
                 "`0x%08X`.\n\n" % OUTER_JUMPS)
        fh.write("%d keywords reach an arm; every other reserved word is "
                 "rejected.\n\n" % sum(len(i) for _f, _a, i in rows))
        fh.write("| id | keyword |\n|---:|---|\n")
        for _first, _arm, ids in rows:
            for i in sorted(ids):
                fh.write("| %d | `%s` |\n" % (i, kw.get(i, "?")))

        fh.write("\n## Nested vocabularies\n\n")
        fh.write("Four arms dispatch again. These are the words each accepts, "
                 "with the ids the range check admits.\n")
        for addr, base, arms in blocks:
            ids = [base + i for i in range(len(arms))]
            if all(kw.get(i) is None for i in ids):
                continue                # the control-character sub-tables
            fh.write("\n### at `0x%08X` -- ids %d..%d\n\n" %
                     (addr, ids[0], ids[-1]))
            fh.write("| id | word |\n|---:|---|\n")
            for i in ids:
                fh.write("| %d | `%s` |\n" % (i, kw.get(i, "?")))

    named = sum(len(i) for _f, _a, i in rows)
    print("-> %s  (%d actions, %d nested tables)"
          % (os.path.relpath(OUT), named, len(blocks)))


if __name__ == "__main__":
    main()
