"""Recover the mission-script token table from the binary.

The game ships its mission scripts as readable text -- data/<map>/<map>N.txt --
and the engine parses them at load. That makes the script language a way IN to
the code: the parser's keyword table maps every name the scripts use to the
number the engine works with, so a function that compares against 29 can be
read as comparing against `everything` rather than against 29.

The table is an array of {const char *name, uint32_t id} at 0x00487A00. Nothing
in the image labels it; it is recognisable because the pointers all land in the
string region and the ids form a dense run from 1.

What it settles so far:

  IsScriptDelim (0x0043EEA0) tests ( ) , < = > { } & + -- exactly the first
  character of each of tokens 1 to 13, which are the language's delimiters and
  comparison operators. That is a confirmation rather than a guess.

  ScriptCompare (0x004374F0) takes 0, 1, 2 for equal, less, greater, which is
  the reduced form of tokens 6, 4 and 7.

  There are four armies -- green, tan, blue, grey -- matching the four names
  the scripts actually use in createtrooper.

Writes docs/scripttokens.md.
"""

import os
import struct
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import am2

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(REPO, "docs", "scripttokens.md")
TABLE_LO, TABLE_HI = 0x00487A00, 0x00488100
STRINGS_LO, STRINGS_HI = 0x00470000, 0x00490000


def tokens(img):
    out = {}
    for base in range(TABLE_LO, TABLE_HI, 8):
        p, v = struct.unpack_from("<II", img.read(base, 8), 0)
        if not (STRINGS_LO <= p < STRINGS_HI):
            continue
        s = img.cstring(p)
        if s is None or not (0 < len(s) < 24) or v > 400:
            continue
        out.setdefault(v, s)
    return out


KIND_TABLE = 0x00487C74      # name pointers indexed by token kind


def kinds(img):
    # Exactly seven. Reading an eighth runs into the token-name array that
    # follows and reports `(` as a token kind.
    out = []
    for k in range(7):
        (p,) = struct.unpack_from("<I", img.read(KIND_TABLE + k * 4, 4), 0)
        if not (STRINGS_LO <= p < STRINGS_HI):
            break
        s = img.cstring(p)
        if not s:
            break
        out.append((k, s))
    return out


def main():
    img = am2.Image()
    tok = tokens(img)
    if not tok:
        print("scripttokens: no table found at %#010x" % TABLE_LO)
        return 1

    groups = [
        ("Delimiters and operators", 1, 13),
        ("Variables and armies", 14, 24),
        ("Entities and pads", 25, 42),
        ("Trigger and flow control", 43, 79),
        ("Actions, weapons and power-ups", 80, 400),
    ]

    with open(OUT, "w") as fh:
        w = fh.write
        w("# The mission-script token table\n\n")
        w("Generated by `tools/scripttokens.py` from the array at "
          "`%#010x`.\n\n" % TABLE_LO)
        w("The scripts themselves are readable text under `data/<map>/`, so "
          "this table\nis how a constant in the engine becomes a word: a "
          "function comparing against\n29 is comparing against `everything`.\n\n")
        w("%d tokens.\n\n" % len(tok))
        for title, lo, hi in groups:
            rows = [(v, s) for v, s in sorted(tok.items()) if lo <= v <= hi]
            if not rows:
                continue
            w("## %s\n\n| id | token |\n|---:|---|\n" % title)
            for v, s in rows:
                w("| %d | `%s` |\n" % (v, s))
            w("\n")
        ks = kinds(img)
        if ks:
            w("## Token kinds\n\n")
            w("Names from the array at `%#010x`, indexed by kind.\n\n"
              "| kind | name |\n|---:|---|\n" % KIND_TABLE)
            for k, s in ks:
                w("| %d | `%s` |\n" % (k, s))
            w("\nThis settles an argument that looked like a magic number: "
              "`LoadLevelScript`\ndeclares each score variable with kind 3, "
              "and kind 3 is `Integer`.\n\n")

        w("## The interpreter\n\n")
        w("```\n"
          "WinMain -> RunFrame -> StateFrame -> LoadLevelScript 0x00425060\n"
          "  -> ParseScriptFile 0x00444CD0 -> ParseScriptLine 0x00444C40\n"
          "    -> NextToken 0x0043F450 -> IsBlank 0x0043EE80, "
          "IsScriptDelim 0x0043EEA0\n"
          "```\n\n")
        w("`LoadLevelScript` builds `<map><n>.txt` when the level index is\n"
          "positive and `<map>.txt` otherwise, resets the context, declares "
          "the five\nscore variables, and parses. It logs `reading script "
          "%s:` and then\n`worked!` or `FAILED!` -- which is how those three "
          "functions are named\nrather than guessed.\n\n")
        w("The tokeniser stops at `/` and `\\`, which is the `//` comment "
          "marker the\nmission scripts actually use.\n\n")

        w("## What this settles\n\n")
        w("`IsScriptDelim` at `0x0043EEA0` accepts `( ) , < = > { } & +` -- "
          "exactly the\nfirst character of each of tokens 1 to 13. "
          "`ScriptCompare` at `0x004374F0`\ntakes 0, 1 and 2 for equal, less "
          "and greater, the reduced form of tokens 6,\n4 and 7.\n\n")
        w("Four armies, `green` `tan` `blue` `grey`, which is what the "
          "scripts use in\n`createtrooper` -- and matches the four-value "
          "range of the army field rather\nthan the eight the uid's three "
          "owner bits could hold.\n")

    print("-> docs/scripttokens.md  (%d tokens)" % len(tok))
    for v in sorted(tok)[:14]:
        print("   %3d  %s" % (v, tok[v]))
    return 0


if __name__ == "__main__":
    sys.exit(main())
