#!/usr/bin/env python3
"""Differential-test the script tokeniser against the words the game ships.

The mission scripts are plain text on disk, so this subsystem can be checked
against real input rather than against synthetic vectors -- and real input is
the better test here: a random 32-bit integer says nothing about a function
whose argument is a keyword. Every distinct word in every shipped .txt goes
through the ORIGINAL under Unicorn, and the answers land in tests/scriptvec.h
for tests/selftest.cpp to replay against the reconstruction.

No part of the game runs. The token table lives in .data, which is mapped from
the file, so the original tokeniser is fully self-contained here.
"""
import os
import re
import struct
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import am2
from vectors import Emu, SCRATCH, SCRATCH_SZ, SCRATCH_PATTERN

GAME_DIR = os.path.join(os.path.dirname(os.path.dirname(
    os.path.abspath(__file__))), ".wine/drive_c/GOG Games/Army Men II")
ADDR_LOOKUP_TOKEN = 0x0043EEE0
OUT = os.path.join(os.path.dirname(os.path.dirname(
    os.path.abspath(__file__))), "tests/scriptvec.h")

# The tokeniser splits on IsScriptDelim and blanks; this is the same split done
# crudely, which is all that is needed to harvest candidate words.
WORD = re.compile(rb"[^\s(),<>={}&+\"]+")


def script_files():
    out = []
    for root, _dirs, names in os.walk(GAME_DIR):
        for n in sorted(names):
            if n.lower().endswith(".txt"):
                out.append(os.path.join(root, n))
    return sorted(out)


def harvest():
    """Every distinct word the shipped scripts contain, plus the delimiters.

    Lower-cased, because the tokeniser lower-cases before looking up and the
    table is lower case throughout -- feeding it `Undeploy` would test the
    caller's _strlwr, which is CRT and not ours.
    """
    words = set()
    for path in script_files():
        with open(path, "rb") as fh:
            for line in fh:
                line = line.split(b"//")[0]
                for m in WORD.finditer(line):
                    w = m.group(0).lower()
                    if 0 < len(w) < 0x40:
                        words.add(w)
    # The one- and two-character operator tokens never survive the word split,
    # and they are ids 1..13 -- the half of the table that would otherwise go
    # untested. NextToken builds them a character at a time and looks them up
    # through this same function.
    for op in (b"(", b")", b",", b"<", b"<=", b"=", b">", b">=", b"<>",
               b"{", b"}", b"&", b"+"):
        words.add(op)
    # A word that is not a keyword must come back -1, and the scripts are full
    # of those already (object names, numbers). One deliberate near-miss per
    # keyword is cheap and tests the walk running off the end.
    words.add(b"")

    # Case variants, because without them the corpus cannot see the difference.
    # Every word above is lower-cased, and lower case is what the table holds,
    # so a reconstruction that compared case-INSENSITIVELY passed all 9,327 --
    # measured, by making exactly that change. The original compares raw bytes
    # and its caller lower-cases first, so `Undeploy` here must come back -1;
    # these are what proves it.
    for w in list(words):
        if w.isalpha():
            words.add(w.capitalize())
            words.add(w.upper())
    return sorted(words)


def main():
    if not os.path.isdir(GAME_DIR):
        sys.exit("no game directory at %s" % GAME_DIR)

    emu = Emu()
    words = harvest()
    rows = []
    for w in words:
        buf = bytearray(SCRATCH_PATTERN[:SCRATCH_SZ])
        buf[0:len(w) + 1] = w + b"\0"
        eax, _mem = emu.call(ADDR_LOOKUP_TOKEN, [SCRATCH], bytes(buf))
        if eax is None:
            sys.exit("emulation failed on %r" % w)
        rows.append((w, struct.unpack("<i", struct.pack("<I", eax))[0]))

    named = sum(1 for _w, v in rows if v >= 0)
    with open(OUT, "w") as fh:
        fh.write("/* Generated by tools/scriptcheck.py -- do not edit.\n *\n"
                 " * Every distinct word in the %d shipped script files, run\n"
                 " * through the original ScriptLookupToken under Unicorn.\n"
                 " * %d of %d resolve to a keyword id.\n */\n"
                 % (len(script_files()), named, len(rows)))
        fh.write("typedef struct { const char *word; int32_t id; } "
                 "AM2_ScriptVec;\n\n")
        fh.write("static const AM2_ScriptVec am2_script_vectors[] = {\n")
        for w, v in rows:
            esc = w.decode("latin-1").replace("\\", "\\\\").replace('"', '\\"')
            fh.write('    { "%s", %d },\n' % (esc, v))
        fh.write("};\n")

    print("-> %s  (%d words, %d keywords, %d files)"
          % (os.path.relpath(OUT), len(rows), named, len(script_files())))


if __name__ == "__main__":
    main()
