"""Recover the mission-script token table from the binary.

The game ships its mission scripts as readable text -- data/<map>/<map>N.txt --
and the engine parses them at load. That makes the script language a way IN to
the code: the parser's keyword table maps every name the scripts use to the
number the engine works with, so a function that compares against 29 can be
read as comparing against `everything` rather than against 29.

The table is an array of {const char *name, uint32_t id} at 0x00487A00. Nothing
in the image labels it; it is recognisable because the pointers all land in the
string region and the ids form a dense run from 1.

What it settles so far:

  IsScriptDelim (0x0043EEA0) tests ( ) , < = > { } & + -- exactly the first
  character of each of tokens 1 to 13, which are the language's delimiters and
  comparison operators. That is a confirmation rather than a guess.

  ScriptCompare (0x004374F0) takes 0, 1, 2 for equal, less, greater, which is
  the reduced form of tokens 6, 4 and 7.

  There are four armies -- green, tan, blue, grey -- matching the four names
  the scripts actually use in createtrooper.

Writes docs/scripttokens.md.
"""

import os
import struct
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import am2

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(REPO, "docs", "scripttokens.md")
# The bounds are not guessed: LookupToken at 0x0043EEE0 walks the table with
# `mov edi, 0x487C90` and stops at `cmp edi, 0x488258`, eight bytes a step. An
# earlier version of this tool guessed 0x487A00..0x488100 and reported 141
# tokens where there are 185 -- `hasitem`, `dropitem`, `isally`, `teamscore`
# and forty others were simply outside the window. Read the loop, not the data.
TABLE_LO, TABLE_HI = 0x00487C90, 0x00488258
STRINGS_LO, STRINGS_HI = 0x00470000, 0x00490000


def tokens(img):
    out = {}
    for base in range(TABLE_LO, TABLE_HI, 8):
        p, v = struct.unpack_from("<II", img.read(base, 8), 0)
        if not (STRINGS_LO <= p < STRINGS_HI):
            continue
        s = img.cstring(p)
        if s is None:
            continue
        out.setdefault(v, s)
    return out


def spellings(img):
    """[(word, id)] for every entry, keeping both of a shared id.

    tokens() collapses to one word per id, which is what the prose table wants;
    the header wants a constant for each spelling, because `mine` and `yours`
    are both 88 and a reader looking up either should find it.
    """
    out = []
    for base in range(TABLE_LO, TABLE_HI, 8):
        p, v = struct.unpack_from("<II", img.read(base, 8), 0)
        if not (STRINGS_LO <= p < STRINGS_HI):
            continue
        s = img.cstring(p)
        if s is not None:
            out.append((s, v))
    return out


KIND_TABLE = 0x00487C74      # name pointers indexed by token kind


def kinds(img):
    # Exactly seven. Reading an eighth runs into the token-name array that
    # follows and reports `(` as a token kind.
    out = []
    for k in range(7):
        (p,) = struct.unpack_from("<I", img.read(KIND_TABLE + k * 4, 4), 0)
        if not (STRINGS_LO <= p < STRINGS_HI):
            break
        s = img.cstring(p)
        if not s:
            break
        out.append((k, s))
    return out


SYMBOLS = {
    "(": "LPAREN", ")": "RPAREN", ",": "COMMA", "<": "LT", "<=": "LE",
    "=": "EQ", ">": "GT", ">=": "GE", "<>": "NE", "{": "LBRACE",
    "}": "RBRACE", "&": "AMP", "+": "PLUS",
}

HEADER = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                      "src/game/scripttokens.h")


def emit_header(tokens, spellings):
    """Constants for every keyword id, generated rather than typed.

    The ids come out of the image, so a generated header cannot drift from the
    table the game itself walks -- which is the same reason the bounds are read
    from ScriptLookupToken's loop instead of guessed.

    Two spellings share id 88, `mine` and `yours`; both get a constant. Ids 15
    and 31 have no entry at all and get none, which is worth knowing because
    the resolver and the pad trigger table each have an arm for one of them
    that nothing can reach.
    """
    with open(HEADER, "w") as fh:
        fh.write("/* Generated by tools/scripttokens.py -- do not edit.\n"
                 " *\n"
                 " * The %d script keywords, from the table ScriptLookupToken\n"
                 " * walks at 0x00487C90. docs/scripttokens.md is the same data\n"
                 " * as prose. Ids 15 and 31 are absent from the table, so no\n"
                 " * constant exists for them and nothing the tokeniser produces\n"
                 " * can carry them.\n */\n"
                 % len(spellings))
        fh.write("#ifndef AM2_SCRIPTTOKENS_H\n#define AM2_SCRIPTTOKENS_H\n\n")
        for name, tid in sorted(spellings, key=lambda t: (t[1], t[0])):
            sym = SYMBOLS.get(name)
            if sym is None:
                sym = name.upper()
            fh.write("#define AM2_TOK_%-16s %3d\n" % (sym, tid))
        fh.write("\n#endif /* AM2_SCRIPTTOKENS_H */\n")


def main():
    img = am2.Image()
    tok = tokens(img)
    if not tok:
        print("scripttokens: no table found at %#010x" % TABLE_LO)
        return 1

    groups = [
        ("Delimiters and operators", 1, 13),
        ("Variables and armies", 14, 24),
        ("Entities and pads", 25, 42),
        ("Trigger and flow control", 43, 79),
        ("Actions, weapons and power-ups", 80, 148),
        ("Queries and later additions", 149, 400),
    ]

    with open(OUT, "w") as fh:
        w = fh.write
        w("# The mission-script token table\n\n")
        w("Generated by `tools/scripttokens.py` from the array at "
          "`%#010x`.\n\n" % TABLE_LO)
        w("The scripts themselves are readable text under `data/<map>/`, so "
          "this table\nis how a constant in the engine becomes a word: a "
          "function comparing against\n29 is comparing against `everything`.\n\n")
        w("%d tokens.\n\n" % len(tok))
        for title, lo, hi in groups:
            rows = [(v, s) for v, s in sorted(tok.items()) if lo <= v <= hi]
            if not rows:
                continue
            w("## %s\n\n| id | token |\n|---:|---|\n" % title)
            for v, s in rows:
                w("| %d | `%s` |\n" % (v, s))
            w("\n")
        ks = kinds(img)
        if ks:
            w("## Token kinds\n\n")
            w("Names from the array at `%#010x`, indexed by kind.\n\n"
              "| kind | name |\n|---:|---|\n" % KIND_TABLE)
            for k, s in ks:
                w("| %d | `%s` |\n" % (k, s))
            w("\nThis settles an argument that looked like a magic number: "
              "`LoadLevelScript`\ndeclares each score variable with kind 3, "
              "and kind 3 is `Integer`.\n\n")

        w("## The interpreter\n\n")
        w("```\n"
          "WinMain -> RunFrame -> StateFrame -> LoadLevelScript 0x00425060\n"
          "  -> ReadScript 0x00444CD0\n"
          "    -> NextToken 0x0043F450 -> IsBlank 0x0043EE80, "
          "IsScriptDelim 0x0043EEA0\n"
          "```\n\n")
        w("`LoadLevelScript` builds `<map><n>.txt` when the level index is\n"
          "positive and `<map>.txt` otherwise, resets the context, declares "
          "the five\nscore variables, and parses. It logs `reading script "
          "%s:` and then\n`worked!` or `FAILED!` -- which is how those three "
          "functions are named\nrather than guessed.\n\n")
        w("The tokeniser stops at `/` and `\\`, which is the `//` comment "
          "marker the\nmission scripts actually use.\n\n")

        w("## The top-level grammar\n\n")
        w("`ReadScript` dispatches on the first token of each statement. A "
          "token is 12\nbytes with its kind at +0 and its id at +8; the "
          "dispatch tests kind == 2,\nwhich the kind table calls `Reserved`, "
          "and then switches on the id.\n\n")
        w("| keyword | id | handler |\n|---|---:|---|\n")
        for kw, tid, h in (("preloadsprite", 25, 0x00444900),
                           ("pad", 26, 0x004440E0),
                           ("variable", 133, 0x00443F70),
                           ("if", 44, 0x004432F0),
                           ("object", 139, 0x00436D60)):
            w("| `%s` | %d | `%#010x` |\n" % (kw, tid, h))
        w("\nThose five are the whole top level, and they are exactly the "
          "statements a\nmission file contains -- `preloadsprite 43 600 1`, "
          "`Pad portal1 99`,\n`object portal1`, `if ... then`. Each handler "
          "is named by the language\nrather than by us.\n\n")

        w("## What a handler tells you about its statement\n\n")
        w("The `pad` handler at `0x004440E0` carries these, and between them "
          "they are a\nspecification:\n\n")
        for msg in ("Duplicate pad name.",
                    "'%s' found, but expected token of type %s",
                    "Unexpected symbol in pad definition should be '<=>'",
                    "Pad can't have both specific item and generic trigger",
                    "Illegal Pad Number"):
            w("- `%s`\n" % msg)
        w("\nSo a pad has a name, which must be unique; a number, which is "
          "range-checked;\nand then EITHER a specific item OR a generic "
          "trigger, never both. A comparison\nfrom `< = >` and a count may "
          "follow. Which is exactly the syntax the missions\nuse:\n\n")
        w("```\n"
          "Pad portal1        99                    name and number\n"
          "Pad victory1       30  GreenSarge1       a specific item\n"
          "Pad rr_burner_pad  20  UNIT              a generic trigger\n"
          "Pad cookie         50  GreenSarge1 > 0   with a comparison\n"
          "```\n\n")
        w("Note the second message: the parser reports the token KIND by name "
          "when it\nrejects something, which is what the kind table above is "
          "for.\n\n")

        w("## What this settles\n\n")
        w("`IsScriptDelim` at `0x0043EEA0` accepts `( ) , < = > { } & +` -- "
          "exactly the\nfirst character of each of tokens 1 to 13. "
          "`ScriptCompare` at `0x004374F0`\ntakes 0, 1 and 2 for equal, less "
          "and greater, the reduced form of tokens 6,\n4 and 7.\n\n")
        w("Four armies, `green` `tan` `blue` `grey`, which is what the "
          "scripts use in\n`createtrooper` -- and matches the four-value "
          "range of the army field rather\nthan the eight the uid's three "
          "owner bits could hold.\n")

    words = spellings(img)
    emit_header(tok, words)
    print("-> docs/scripttokens.md + src/game/scripttokens.h  (%d ids, "
          "%d spellings)" % (len(tok), len(words)))
    for v in sorted(tok)[:14]:
        print("   %3d  %s" % (v, tok[v]))
    return 0


if __name__ == "__main__":
    sys.exit(main())
